config/routes.rb
Rails.application.routes.draw do
  get 'trainings/show'
  get 'trainings/new'
  get 'trainings/index'
  root 'sessions#index'
  
  #custom routes for login
  #creating a new session
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy' #this needs to be a delete action because you dont want '/logout' to be an option that can be typed in the url, but rather a button to click on a page

  #can't log in without a user
  #custom routes for signup
  #creating a new model object
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  resources :workouts do
    resources :trainings, only: [:index, :new, :create] #2021-01-15
  end
  resources :trainings
  resources :races do # 2021-01-16 01
    resources :trainings # 2021-01-16 01
  end# 2021-01-16 01
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :race
  belongs_to :workout

  scope :by_workout, -> (workout_id) {where("workout_id = ?", workout_id)} #2021-01-15 01

  validates :date, presence: true #2021-01-15 01
  validates_associated :workout #2021-01-15 02 training wont save unless workout is valid
  #accepts_nested_attributes_for :workout
    # :workout needs to match with the way the model association is named

  def workout_attributes=(workout_params)
    workout = Workout.find_or_create_by(workout_params)
    workout_params[:name].empty? ? self.workout : self.workout = workout #2021-01-15 02
    # workout.valid? ? self.workout = workout : self.workout
    # 2021-01-15 01 added above line, removed workout/valid lines
    # if workout.valid?
    #   self.workout = workout
    # end
  end
  
  def datetime #2021-01-16 02 moved here for easy access to modify
    self.date.strftime("%A, %b %d") if self.date
    #self.date.try(:strftime, "%A, %b %d") this does the same as thing as the line above
  end

  def username #2021-01-17
    @username ||= self.race.try(:user).try(:username) # 2021-01-17 moved here from app/views/trainings/index.html.erb
  end

end

# 2021-01-16 02 code that involves your database should go in your model
# 2021-01-16 02 anything to do with "sorting" or "ordering" goes in a scope method in the model

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  def show
    @training = Training.find(params[:id])
  end

  def index #2021-01-15 added index action
    #if it's nested
    if params[:workout_id] && @workout = Workout.find_by_id(params[:workout_id]) #2021-01-16 01
      @trainings = @workout.trainings #2021-01-16 01

    #load up ony the trainings nested under that workout
  elsif params[:race_id] && @race = Race.find_by_id(params[:race_id]) #2021-01-16 01
    @trainings = @race.trainings #2021-01-16 01
  else
    #keep with the same old stuff
    @trainings = Training.all
    end
  end
  

  def new #2021-01-15
    #if it's nested
    if params[:workout_id] && @workout = Workout.find_by_id(params[:workout_id])
      @training = @workout.trainings.build #has_many

    #load up ony the trainings nested under that workout
    else
      #else keep with the same old stuff
      @training = Training.new
      @training.build_workout  #belongs_to - nested form
    end
  end

  def create #2021-01-15
    if params[:workout_id] && @workout = Workout.find_by_id(params[:workout_id])
     @training = @workout.trainings.build(training_params)
    else
     @training = Training.new(training_params)
    end
    if @training.save
     redirect_to training_path(@training)
    else
     render :new
    end
 end

  private

  def training_params
    params.require(:training).permit(:date,:feeling, :race_id, :workout_id, workout_attributes:[:name, :category, :pace, :distance, :user_id])
  end
          # require the model
        # permit the attributes you want to allow in
        # strong params
end

app/helpers/trainings_helper.rb
module TrainingsHelper

    def display_index_header
        # 2021-01-16 02 moved the training sessions workout name, race title from the app/views/trainings/index.html.erb
        if @workout
            content_tag(:h2,"Training Sessions for the  #{@workout.name} workout")
        elsif @race
            tag.h2("Training Sessions for the #{@race.title} race")
        else
            content_tag(:h1, "All Training Sessions")
        end
    end

    def display_date(t) # 2021-01-17 moved here from app/views/trainings/index.html.erb
        "on #{t.datetime}" if t.date
    end
    
    def display_feeling(t) # 2021-01-17 moved here from app/views/trainings/index.html.erb
        "and felt: #{t.feeling}"  if !t.feeling.empty?
    end

    def workout_form_option(form_builder) # 2021-01-17 moved here from app/views/trainings/new.html.erb
         if @workout  #  2021-01-15
            content_tag(:p, "Workout: #{@workout.name}")
             else 
                #    2021-01-17 moved the "select a workout" and "create a workout" to app/views/trainings/_workoutform.html.erb
                render partial: "workoutform", locals: {f: form_builder} 
                #   2021-01-17 added a render partial
               end 
    end
    
end

app/views/trainings/_workoutform.html.erb
<%= f.label :workout_id, "Select a workout:" %>
  <%= f.collection_select :workout_id, Workout.all, :id, :name, include_blank: true    %> <!-- gives a dropdown menu of  the workouts that were created and stored in the database-->

   <br><br>

   <h3>Or Create a new workout:</h3>
   <%= render partial: "layouts/errors", locals: { object: @training.workout } %> <!-- 2021-01-15 02-->

  <%= f.fields_for :workout do |w| %>
    <%= w.label :name %>
  <%= w.text_field :name %>
    <br><br>

  <%= w.label :category %>
  <%= w.select :category,options_for_select(["run", "swim", "bike", "walk", "weights", "other"]), include_blank: true  %><!-- gives a dropdown menu -->
    <br><br>

  <%= w.label :pace %>
  <%= w.text_field :pace %>
  <br><br>

  <%= w.label :distance, "Distance in Miles" %>
  <%= w.text_field :distance %>
    <br><br>

  <%= w.hidden_field :user_id, value: current_user.id %>
    <br><br>
  <% end %><!-- 2021-01-15 -->

app/views/trainings/index.html.erb
<!-- 2021-01-16 02 moved the training sessions workout name, race title to app/helpers/trainings_helper.rb -->

<%= display_index_header %> <!-- 2021-01-17 linked to app/helpers/trainings_helper.rb -->


<ul>
<% @trainings.order(:date).each do |t| %>
<li>
    <%= t.username %> completed the <!-- 2021-01-17 -->
    <%= link_to t.workout.name, workout_path(t.workout)%>
    while training for the <%= link_to t.race.title, race_path(t.race)%>
    <%= display_date(t) %> <!-- 2021-01-17 app/helpers/trainings_helper.rb -->
    <%= display_feeling(t) %> <!-- 2021-01-17 app/helpers/trainings_helper.rb -->
  </li><br>
<% end %>
</ul>
 <!-- 2021-01-16 01 -->

 <!-- 2021-01-16 02 code that involves your database should go in your model -->
 <!-- 2021-01-16 02 anything to do with "sorting" or "ordering" goes in a scope method in the model -->

app/views/trainings/new.html.erb
<h1>Record a Training Session</h1>

<%= render partial: "layouts/errors", locals: { object: @training } %> <!-- 2021-01-15 02-->

<%= form_for [@workout,@training] do |f| %><!-- 2021-01-15-->
<!-- if there is an error here, it could because the "new" method isn't definded in the trainings_controller-->
  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :feeling %>
  <%= f.text_field :feeling %>

  <br><br>

  <%= f.label :race_id %>
  <%= f.collection_select :race_id, current_user.races, :id, :title    %> <!-- gives a dropdown menu of  the races that were created and stored in the database-->

  <br><br>
  <%= workout_form_option(f) %> <!-- 2021-01-17 linked to app/helpers/trainings_helper.rb -->
  <%= f.submit%>
 
<% end %> 

app/views/trainings/show.html.erb
<h1>Workout: <%= @training.workout.name %></h1>



<h2>Race: <%=@training.race.title%>
<h3><%= @training.workout.category %>  | <%= @training.workout.distance %> miles</h3><!-- 2021-01-15 -->

<p>Date: <%= @training.date %>  </p><!-- 2021-01-15 -->

<p>Feeling: <%= @training.feeling %></p><!-- 2021-01-15 -->