config/routes.rb
Rails.application.routes.draw do
  get 'trainings/show'
  get 'trainings/new'
  get 'trainings/index'
  root 'sessions#index'
  
  #custom routes for login
  #creating a new session
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy' #this needs to be a delete action because you dont want '/logout' to be an option that can be typed in the url, but rather a button to click on a page

  #can't log in without a user
  #custom routes for signup
  #creating a new model object
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  resources :workouts do
    resources :trainings, only: [:index, :new, :create] #2021-01-15
  end
  resources :trainings
  resources :races do # 2021-01-16 01
    resources :trainings # 2021-01-16 01
  end# 2021-01-16 01
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
class Workout < ApplicationRecord
    has_many :trainings
    has_many :races, through: :trainings
    belongs_to :user

    validates :name, :distance, presence: true # 2021-01-15 01 added

    scope :order_by_popularity, -> { Workout.left_joins(:trainings).group(:id).order("count(trainings.workout_id) desc") } # 2021-01-15 02
    #order by how many training sessions
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :set_workout, only: [:show] #2021-01-16 02
    
    def index
        # @workouts = Workout.all # 2021-01-15 02
        @workouts = Workout.order_by_popularity # 2021-01-15 02
    end
  
    def show #2021-01-16 02 
    end
  
    def new
      @workout = Workout.new
    end
  
    def create
        @workout = current_user.created_workouts.build(workout_params)
        if @workout.save
         redirect_to workout_path(@workout)
         # it will redirect to the workout#show page
         # anytime it's going to forom url that needs a dynamic route or id, an instance needs to be used
        else
         render :new
        end
    end
    private

    def workout_params
     params.require(:workout).permit(:pace, :distance, :name, :category)
             # require the model
        # permit the attributes you want to allow in
        # strong params
    end

    def set_workout # finding an instance # 2021-01-16 02
        @workout = Workout.find_by(id: params[:id])
        redirect_to workouts_path if !@workout #redirect to all of the workouts if a specifc workout was not found from the params :id
     end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/index.html.erb
<h1>All Workouts</h1>

<ul>
<% @workouts.each do |workout| %>
<li>
  <strong><%= workout.name %></strong> -
  <%=workout.distance %> miles  -
  <%=workout.pace %> - added by: <%= workout.user.username%> <!--2021-01-15 -->
  <%= link_to "See all training sessions", workout_trainings_path(workout)%> | <!--2021-01-15 -->
  <%= link_to "Add a training session", new_workout_training_path(workout)%> <!--2021-01-15 -->
</li>

<% end %>
</ul> 

app/views/workouts/new.html.erb
<h1>Add a New Workout</h1>
<%= form_for @workout do |f| %>

 <%= f.label :name %>
  <%= f.text_field :name %>
    <br><br>

  <%= f.label :category %>
  <%= f.select :category,options_for_select(["run", "swim", "bike", "walk", "weights", "other"]), include_blank: true  %>
    <br><br>

  <%= f.label :pace %>
  <%= f.text_field :pace %>
  <br><br>

  <%= f.label :distance, "Distance in Miles" %>
  <%= f.text_field :distance %>
    <br><br>

  <%= f.submit%>

<% end %> 

app/views/workouts/show.html.erb
<h1><%= @workout.name %></h1>
<p><%=@workout.distance %> miles</p>
<%=@workout.pace %>