config/routes.rb
Rails.application.routes.draw do
  get 'trainings/show'
  get 'trainings/new'
  get 'trainings/index'
  root 'sessions#index'
  
  #custom routes for login
  #creating a new session
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy' #this needs to be a delete action because you dont want '/logout' to be an option that can be typed in the url, but rather a button to click on a page

  #can't log in without a user
  #custom routes for signup
  #creating a new model object
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  resources :workouts do
    resources :trainings, only: [:index, :new, :create] #2021-01-15
  end
  resources :trainings
  resources :races do # 2021-01-16 01
    resources :trainings # 2021-01-16 01
  end# 2021-01-16 01
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.try(:errors).try(:any?) %> <!--.try makes sure that if theres a nil, it wont show an error when you chain methods together. it will skip doing that method if would show an error if there is a nil value. so this entire block of code would get ignored, if there is an error if there is a nil value.-->
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<!-- 2021-01-15 02 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutPlanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in? %>
      <%= link_to 'Logout', '/logout', method: :delete%> |
      <%= link_to 'My Races', races_path %> |
      <%= link_to 'Add a Race', new_race_path %> |
      <%= link_to 'Add a Workout', new_workout_path %> |
      <%= link_to 'All Workouts', workouts_path %> | <!--2021-01-15-->
      <%= link_to 'Add a Training Session', new_training_path %> | <!--2021-01-15-->
      <%= link_to 'My Training Sessions', trainings_path %> <!--2021-01-15-->
    <% else %>
      <%= link_to 'Log In', login_path %>
    <% end %>

    <%= yield %>
  </body>
</html>